project:
  type: website

website:
  title: "Donggyu Kim"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto  # only render the files I changed.

