project:
  type: website

website:
  title: "Donggyu Kim"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: experience.qmd
        text: Work Experience
      - href: course.qmd
        text: Courses
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto  # only render the files I changed.

